sequences = {'nome': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me1': {'bdna+bdna': {'guide': 'CGCGXGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me2': {'bdna+bdna': {'guide': 'CGCGCGXGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me3': {'bdna+bdna': {'guide': 'CGCGCGCGXGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me12': {'bdna+bdna': {'guide': 'CGCGXGXGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me23': {'bdna+bdna': {'guide': 'CGCGCGXGXGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me123': {'bdna+bdna': {'guide': 'CGCGXGXGXGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             '21_nome': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCGCGCGCGCG'}},
             '21_allme': {'bdna+bdna': {'guide': 'CGXGXGXGXGXGXGXGXGXGC',
                                    'target': 'GXGXGXGXGXGXGXGXGXGXG'}}
             }
