sequences = {'nome': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me1': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me2': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me3': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me12': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me23': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}},
             'me123': {'bdna+bdna': {'guide': 'CGCGCGCGCGCGC',
                                    'target': 'GCGCGCGCGCGCG'}}
             }
